using Eduplos.Domain.AcademicModule;
using Eduplos.Domain.CoreModule;
using KS.Core.UserManagement;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace KS.Data
{
    internal class DBInitializer: CreateDatabaseIfNotExists<UnitOfWork>
    {

        
        private string GenerateSalt()
        {
            RNGCryptoServiceProvider random = new RNGCryptoServiceProvider();
            byte[] salt = new byte[64];//512 bits
            random.GetBytes(salt);
            return BytesToHex(salt);

        }

        public string HashedPassword(string password)
        {
            string salt = GenerateSalt();
            string hash = Sha512Hex(salt + password);

            return salt + hash;
        }

        private string Sha512Hex(string toHash)
        {
            SHA512Managed sha = new SHA512Managed();
            byte[] utf8 = UTF8Encoding.UTF8.GetBytes(toHash);
            return BytesToHex(sha.ComputeHash(utf8));
        }


        private string BytesToHex(byte[] toConvert)
        {
            StringBuilder sbuilder = new StringBuilder(toConvert.Length * 2);
            foreach (byte b in toConvert)
            {
                sbuilder.Append(b.ToString("x2"));
            }
            return sbuilder.ToString();
        }
        protected override void Seed(UnitOfWork context)
        {




            var ur = new List<Role>
            {

                new Role{RoleName="Administrator",IsSystemAdmin=true},
                new Role{RoleName="Exams Officer"},
                new Role{RoleName="HOD"},
                new Role{RoleName="VC"},
                new Role{RoleName="Student"},
                new Role{RoleName="Prospective"}
            };

            foreach (var u in ur)
            {
                context.Role.Add(u);
                context.SaveChanges();
            }

            
            User user = new User();
            user.UserId = "000001";
            user.UserName="Admin";
            
            user.FullName = "Administrator";
            user.IsActive=true;
            user.LastActivityDate=DateTime.UtcNow;
            user.CreateDate=DateTime.UtcNow;
            var userRoles=context.Role.Where(r=>r.RoleName=="Administrator").FirstOrDefault();
            user.UserRoles.Add(userRoles);
            user.Password = HashedPassword("password");
            user.LoginCounter = 0;

            context.User.Add(user);
            context.SaveChanges();

            
            var progs = new List<ProgrammeTypes>
            {
                new ProgrammeTypes{Type="NCE",IsActive=true},
               
            };

            foreach(var d in progs)
            {
                context.ProgrammeType.Add(d);
                context.SaveChanges();
            }
             
            var countries = new List<Country>
            {
                new Country() { CountryName ="Nigeria"  },
                new Country(){CountryName = "Ghana"},
                new Country(){CountryName = "Benin"}

            };

            foreach (var c in countries)
            {
                context.Country.Add(c);
                context.SaveChanges();
            }

            var states = new List<State>
            {
                new State(){StateName="Abia", CountryId="NG"},
                new State(){StateName="Abuja FCT", CountryId="NG"},
                new State(){StateName="Adamawa", CountryId="NG"},
                new State(){StateName="Akwa Ibom", CountryId="NG"},
                new State(){StateName="Anambra", CountryId="NG"},
                new State(){StateName="Bauchi", CountryId="NG"},
                new State(){StateName="Bayelsa", CountryId="NG"},
                new State(){StateName="Benue", CountryId="NG"},
                new State(){StateName="Borno", CountryId="NG"},
                new State(){StateName="Cross Rivers", CountryId="NG"},
                new State(){StateName="Delta", CountryId="NG"},
                new State(){StateName="Ebonyi", CountryId="NG"},
                new State(){StateName="Edo", CountryId="NG"},
                new State(){StateName="Ekiti", CountryId="NG"},
                new State(){StateName="Enugu", CountryId="NG"},
                new State(){StateName="Gombe", CountryId="NG"},
                new State(){StateName="Imo", CountryId="NG"},
                new State(){StateName="Jigawa", CountryId="NG"},
                new State(){StateName="Kaduna", CountryId="NG"},
                new State(){StateName="Kano", CountryId="NG"},
                new State(){StateName="Katsina", CountryId="NG"},
                new State(){StateName="Kebbi", CountryId="NG"},
                new State(){StateName="Kogi", CountryId="NG"},
                new State(){StateName="Kwara", CountryId="NG"},
                new State(){StateName="Lagos", CountryId="NG"},
                new State(){StateName="Nasarawa", CountryId="NG"},
                new State(){StateName="Niger", CountryId="NG"},
                new State(){StateName="Ogun", CountryId="NG"},
                new State(){StateName="Ondo", CountryId="NG"},
                new State(){StateName="Osun", CountryId="NG"},
                new State(){StateName="Oyo", CountryId="NG"},
                new State(){StateName="Plateau", CountryId="NG"},
                new State(){StateName="Rivers", CountryId="NG"},
                new State(){StateName="Sokoto", CountryId="NG"},
                new State(){StateName="Taraba", CountryId="NG"},
                new State(){StateName="Yobe", CountryId="NG"},
                new State(){StateName="Zamfara", CountryId="NG"},

            };

            foreach (var s in states)
            {
                context.State.Add(s);
                context.SaveChanges();
            }

/*
            var lgs = new List<LGA>
            {
                new LGA(){LgTitle="Aba North",StateId=1},
                new LGA(){LgTitle="Aba South",StateId=1},
                new LGA(){LgTitle="Abadam",StateId=9},
                new LGA(){LgTitle="Abuji",StateId=2},
                new LGA(){LgTitle="Abak",StateId=4},
                new LGA(){LgTitle="Abakaliki",StateId=12},
                new LGA(){LgTitle="Abeokuta-North",StateId=28},
                new LGA(){LgTitle="Abeokuta-South",StateId=28},
                new LGA(){LgTitle="Abi",StateId=10},
                new LGA(){LgTitle="Aboh-Mbaise",StateId=17},
                new LGA(){LgTitle="Abua/Odual",StateId=33},
                new LGA(){LgTitle="Abuja Municipal Area",StateId=2},
                new LGA(){LgTitle="Adavi",StateId=23},
                new LGA(){LgTitle="Ado",StateId=8},
                new LGA(){LgTitle="Ado Ekiti",StateId=14},
                new LGA(){LgTitle="Ado-Odo/Ota",StateId=28},
                new LGA(){LgTitle="Afijio",StateId=31},
                new LGA(){LgTitle="Afikpo North",StateId=12},
                new LGA(){LgTitle="Afikpo South",StateId=12},
                new LGA(){LgTitle="Agaie",StateId=27},
                new LGA(){LgTitle="Agatu",StateId=8},
                new LGA(){LgTitle="Agege",StateId=25},
                new LGA(){LgTitle="Ago-Oluwa",StateId=31},
                new LGA(){LgTitle="Aguata",StateId=5},
                new LGA(){LgTitle="Agwara",StateId=27},
                new LGA(){LgTitle="Agwu",StateId=15},
                new LGA(){LgTitle="Ahiazu-Mbaise",StateId=17},
                new LGA(){LgTitle="Ahoada East",StateId=33},
                new LGA(){LgTitle="Ahoada West",StateId=33},
                new LGA(){LgTitle="Aiyedade",StateId=30},
                new LGA(){LgTitle="Aiyedire",StateId=30},
                new LGA(){LgTitle="Aiyekire",StateId=14},
                new LGA(){LgTitle="Ajaokuta",StateId=23},
                new LGA(){LgTitle="Ajeromi-Ifelodun",StateId=25},
                new LGA(){LgTitle="Ajingi",StateId=20},
                new LGA(){LgTitle="Akampka",StateId=10},
                new LGA(){LgTitle="Akinyele",StateId=31},
                new LGA(){LgTitle="Akko",StateId=16},
                new LGA(){LgTitle="Akoko Edo",StateId=13},
                new LGA(){LgTitle="Akoko North East",StateId=29},
                new LGA(){LgTitle="Akoko North West",StateId=29},
                new LGA(){LgTitle="Akoko South East",StateId=29},
                new LGA(){LgTitle="Akoko South West",StateId=29},
                new LGA(){LgTitle="Akpabuyo",StateId=10},
                new LGA(){LgTitle="Akuku-Toru",StateId=33},
                new LGA(){LgTitle="Akure North",StateId=29},
                new LGA(){LgTitle="Akure South",StateId=29},
                new LGA(){LgTitle="Akwanga",StateId=26},
                new LGA(){LgTitle="Albasu",StateId=20},
                new LGA(){LgTitle="Aleiro",StateId=22},
                new LGA(){LgTitle="Alimosho",StateId=25},
                new LGA(){LgTitle="Alkaleri",StateId=6},
                new LGA(){LgTitle="Amuwo-Odofin",StateId=25},
                new LGA(){LgTitle="Anambra East",StateId=5},
                new LGA(){LgTitle="Anambra West",StateId=5},
                new LGA(){LgTitle="Anaocha",StateId=5},
                new LGA(){LgTitle="Andoni",StateId=33},
                new LGA(){LgTitle="Aninri",StateId=15},
                new LGA(){LgTitle="Aniocha North",StateId=11},
                new LGA(){LgTitle="Aniocha South",StateId=11},
                new LGA(){LgTitle="Anka",StateId=37},
                new LGA(){LgTitle="Ankpa",StateId=23},
                new LGA(){LgTitle="Apa",StateId=8},
                new LGA(){LgTitle="Apapa",StateId=25},
                new LGA(){LgTitle="Ardo-Kola",StateId=35},
                new LGA(){LgTitle="Arewa-Dandi",StateId=22},
                new LGA(){LgTitle="Argungu",StateId=22},
                new LGA(){LgTitle="Arochukwu",StateId=1},
                new LGA(){LgTitle="Asa",StateId=24},
                new LGA(){LgTitle="Asari-Toru",StateId=33},
                new LGA(){LgTitle="Askira/Uba",StateId=9},
                new LGA(){LgTitle="Atakumosa East",StateId=30},
                new LGA(){LgTitle="Atakumosa West",StateId=30},
                new LGA(){LgTitle="Atiba",StateId=31},
                new LGA(){LgTitle="Atigbo",StateId=31},
                new LGA(){LgTitle="Augie",StateId=22},
                new LGA(){LgTitle="Auyo",StateId=18},
                new LGA(){LgTitle="Awe",StateId=26},
                new LGA(){LgTitle="Awka North",StateId=5},
                new LGA(){LgTitle="Awka South",StateId=5},
                new LGA(){LgTitle="Ayamelum",StateId=5},
                new LGA(){LgTitle="Babura",StateId=18},
                new LGA(){LgTitle="Badagry",StateId=25},
                new LGA(){LgTitle="Bade",StateId=36},
                new LGA(){LgTitle="Bagudo",StateId=22},
                new LGA(){LgTitle="Bagwai",StateId=20},
                new LGA(){LgTitle="Bakassi",StateId=10},
                new LGA(){LgTitle="Bakori",StateId=21},
                new LGA(){LgTitle="Bakura",StateId=37},
                new LGA(){LgTitle="Balanga",StateId=16},
                new LGA(){LgTitle="Bali",StateId=35},
                new LGA(){LgTitle="Bama",StateId=9},
                new LGA(){LgTitle="Barikin Ladi",StateId=32},
                new LGA(){LgTitle="Baruten",StateId=24},
                new LGA(){LgTitle="Bassa",StateId=23},
                new LGA(){LgTitle="Bassa-P",StateId=32},
                new LGA(){LgTitle="Batagarawa",StateId=21},
                new LGA(){LgTitle="Batsari",StateId=21},
                new LGA(){LgTitle="Bauchi",StateId=6},
                new LGA(){LgTitle="Baure",StateId=21},
                new LGA(){LgTitle="Bayo",StateId=9},
                new LGA(){LgTitle="Bebji",StateId=20},
                new LGA(){LgTitle="Bekwarra",StateId=10},
                new LGA(){LgTitle="Bende",StateId=1},
                new LGA(){LgTitle="Biase",StateId=10},
                new LGA(){LgTitle="Bichi",StateId=20},
                new LGA(){LgTitle="Bida",StateId=27},
                new LGA(){LgTitle="Billiri",StateId=16},
                new LGA(){LgTitle="Bindawa",StateId=21},
                new LGA(){LgTitle="Binji",StateId=34},
                new LGA(){LgTitle="Birnin Gwari",StateId=19},
                new LGA(){LgTitle="Birnin-Kebbi",StateId=22},
                new LGA(){LgTitle="Birnin-Kudu",StateId=18},
                new LGA(){LgTitle="Birnin-Magaji",StateId=37},
                new LGA(){LgTitle="Birniwa",StateId=18},
                new LGA(){LgTitle="Biu",StateId=9},
                new LGA(){LgTitle="Bodinga",StateId=34},
                new LGA(){LgTitle="Bogoro",StateId=6},
                new LGA(){LgTitle="Boki",StateId=10},
                new LGA(){LgTitle="Bokkos",StateId=32},
                new LGA(){LgTitle="Boluwaduro",StateId=30},
                new LGA(){LgTitle="Bomadi",StateId=11},
                new LGA(){LgTitle="Bonny",StateId=33},
                new LGA(){LgTitle="Borgu",StateId=27},
                new LGA(){LgTitle="Boripe",StateId=30},
                new LGA(){LgTitle="Bosari",StateId=36},
                new LGA(){LgTitle="Bosso",StateId=27},
                new LGA(){LgTitle="Brass",StateId=7},
                new LGA(){LgTitle="Buja",StateId=18},
                new LGA(){LgTitle="Bukkuyum",StateId=37},
                new LGA(){LgTitle="Bungudu",StateId=37},
                new LGA(){LgTitle="Bunkure",StateId=20},
                new LGA(){LgTitle="Bunza",StateId=22},
                new LGA(){LgTitle="Buruku",StateId=8},
                new LGA(){LgTitle="Burutu",StateId=11},
                new LGA(){LgTitle="Bwari",StateId=2},
                new LGA(){LgTitle="Calabar Municipal",StateId=10},
                new LGA(){LgTitle="Calabar South",StateId=10},
                new LGA(){LgTitle="Chanchaga",StateId=27},
                new LGA(){LgTitle="Charanchi",StateId=21},
                new LGA(){LgTitle="Chibok",StateId=9},
                new LGA(){LgTitle="Chikun",StateId=19},
                new LGA(){LgTitle="Dala",StateId=20},
                new LGA(){LgTitle="Damaturu",StateId=36},
                new LGA(){LgTitle="Damban",StateId=6},
                new LGA(){LgTitle="Dambatta",StateId=20},
                new LGA(){LgTitle="Damboa",StateId=9},
                new LGA(){LgTitle="Dandi",StateId=22},
                new LGA(){LgTitle="Dandume",StateId=21},
                new LGA(){LgTitle="Dange-Shuni",StateId=34},
                new LGA(){LgTitle="Danja",StateId=21},
                new LGA(){LgTitle="Danmusa",StateId=21},
                new LGA(){LgTitle="Darazo",StateId=6},
                new LGA(){LgTitle="Dass",StateId=6},
                new LGA(){LgTitle="Daura",StateId=21},
                new LGA(){LgTitle="Dawakin-Kudu",StateId=20},
                new LGA(){LgTitle="Dawakin-Tofa",StateId=20},
                new LGA(){LgTitle="Degema",StateId=33},
                new LGA(){LgTitle="Dekina",StateId=23},
                new LGA(){LgTitle="Demsa",StateId=3},
                new LGA(){LgTitle="Dikwa",StateId=9},
                new LGA(){LgTitle="Doguwa",StateId=20},
                new LGA(){LgTitle="Doma",StateId=26},
                new LGA(){LgTitle="Donga",StateId=35},
                new LGA(){LgTitle="Dukku",StateId=16},
                new LGA(){LgTitle="Dunukofia",StateId=5},
                new LGA(){LgTitle="Dutse",StateId=18},
                new LGA(){LgTitle="Dutsi",StateId=21},
                new LGA(){LgTitle="Dutsin-Ma",StateId=21},
                new LGA(){LgTitle="Eastern Obolo",StateId=4},
                new LGA(){LgTitle="Ebonyi",StateId=12},
                new LGA(){LgTitle="Edati",StateId=27},
                new LGA(){LgTitle="Ede North",StateId=30},
                new LGA(){LgTitle="Ede South",StateId=30},
                new LGA(){LgTitle="Edu",StateId=24},
                new LGA(){LgTitle="Efon",StateId=14},
                new LGA(){LgTitle="Egbado North",StateId=28},
                new LGA(){LgTitle="Egbado South",StateId=28},
                new LGA(){LgTitle="Egbeda",StateId=31},
                new LGA(){LgTitle="Egbedore",StateId=30},
                new LGA(){LgTitle="Egor",StateId=13},
                new LGA(){LgTitle="Ehime-Mnabo",StateId=17},
                new LGA(){LgTitle="Ejigbo",StateId=30},
                new LGA(){LgTitle="Ekeremor",StateId=7},
                new LGA(){LgTitle="Eket",StateId=4},
                new LGA(){LgTitle="Ekiti",StateId=24},
                new LGA(){LgTitle="Ekiti East",StateId=14},
                new LGA(){LgTitle="Ekiti South West",StateId=14},
                new LGA(){LgTitle="Ekiti West",StateId=14},
                new LGA(){LgTitle="Ekwusigo",StateId=5},
                new LGA(){LgTitle="Eleme",StateId=33},
                new LGA(){LgTitle="Emuoha",StateId=33},
                new LGA(){LgTitle="Emure",StateId=14},
                new LGA(){LgTitle="Enugu East",StateId=15},
                new LGA(){LgTitle="Enugu North",StateId=15},
                new LGA(){LgTitle="Enugu South",StateId=15},
                new LGA(){LgTitle="Epe",StateId=25},
                new LGA(){LgTitle="Esan Central",StateId=13},
                new LGA(){LgTitle="Esan North East",StateId=13},
                new LGA(){LgTitle="Esan South East",StateId=13},
                new LGA(){LgTitle="Esan West",StateId=13},
                new LGA(){LgTitle="Ese Odo",StateId=29},
                new LGA(){LgTitle="Esiteket",StateId=4},
                new LGA(){LgTitle="Essien Udim",StateId=4},
                new LGA(){LgTitle="Etche",StateId=33},
                new LGA(){LgTitle="Ethiope East",StateId=11},
                new LGA(){LgTitle="Ethiope West",StateId=11},
                new LGA(){LgTitle="Etim Ekpo",StateId=4},
                new LGA(){LgTitle="Etinan",StateId=4},
                new LGA(){LgTitle="Eti-Osa",StateId=25},
                new LGA(){LgTitle="Etsako Central",StateId=13},
                new LGA(){LgTitle="Etsako East",StateId=13},
                new LGA(){LgTitle="Etsako West",StateId=13},
                new LGA(){LgTitle="Etung",StateId=10},
                new LGA(){LgTitle="Ewekoro",StateId=28},
                new LGA(){LgTitle="Ezeagu",StateId=15},
                new LGA(){LgTitle="Ezihinitte",StateId=17},
                new LGA(){LgTitle="Ezza North",StateId=12},
                new LGA(){LgTitle="Ezza South",StateId=12},
                new LGA(){LgTitle="Fagge",StateId=20},
                new LGA(){LgTitle="Fakai",StateId=22},
                new LGA(){LgTitle="Faskari",StateId=21},
                new LGA(){LgTitle="Fika",StateId=36},
                new LGA(){LgTitle="Fufore",StateId=3},
                new LGA(){LgTitle="Funakaye",StateId=16},
                new LGA(){LgTitle="Fune",StateId=36},
                new LGA(){LgTitle="Funtua",StateId=21},
                new LGA(){LgTitle="Gabasawa",StateId=20},
                new LGA(){LgTitle="Gada",StateId=34},
                new LGA(){LgTitle="Gagarawa",StateId=18},
                new LGA(){LgTitle="Gamawa",StateId=6},
                new LGA(){LgTitle="Ganjuwa",StateId=6},
                new LGA(){LgTitle="Ganye",StateId=3},
                new LGA(){LgTitle="Garki",StateId=18},
                new LGA(){LgTitle="Garko",StateId=20},
                new LGA(){LgTitle="Garum-Mallam",StateId=20},
                new LGA(){LgTitle="Gashaka",StateId=35},
                new LGA(){LgTitle="Gassol",StateId=35},
                new LGA(){LgTitle="Gaya",StateId=20},
                new LGA(){LgTitle="Gbako",StateId=27},
                new LGA(){LgTitle="Gboko",StateId=8},
                new LGA(){LgTitle="Geidam",StateId=36},
                new LGA(){LgTitle="Gezawa",StateId=20},
                new LGA(){LgTitle="Giade",StateId=6},
                new LGA(){LgTitle="Girei",StateId=3},
                new LGA(){LgTitle="Giwa",StateId=19},
                new LGA(){LgTitle="Gokana",StateId=33},
                new LGA(){LgTitle="Gombe",StateId=16},
                new LGA(){LgTitle="Gombi",StateId=3},
                new LGA(){LgTitle="Goronyo",StateId=34},
                new LGA(){LgTitle="Gubio",StateId=9},
                new LGA(){LgTitle="Gudu",StateId=34},
                new LGA(){LgTitle="Gujba",StateId=36},
                new LGA(){LgTitle="Gulani",StateId=36},
                new LGA(){LgTitle="Guma",StateId=8},
                new LGA(){LgTitle="Gumel",StateId=18},
                new LGA(){LgTitle="Gummu",StateId=37},
                new LGA(){LgTitle="Gurara",StateId=27},
                new LGA(){LgTitle="Guri",StateId=18},
                new LGA(){LgTitle="Gusau",StateId=37},
                new LGA(){LgTitle="Guyuk",StateId=3},
                new LGA(){LgTitle="Guzamala",StateId=9},
                new LGA(){LgTitle="Gwadabawa",StateId=34},
                new LGA(){LgTitle="Gwagwalada",StateId=2},
                new LGA(){LgTitle="Gwale",StateId=20},
                new LGA(){LgTitle="Gwandu",StateId=22},
                new LGA(){LgTitle="Gwaram",StateId=18},
                new LGA(){LgTitle="Gwarzo",StateId=20},
                new LGA(){LgTitle="Gwer East",StateId=8},
                new LGA(){LgTitle="Gwer West",StateId=8},
                new LGA(){LgTitle="Gwiwa",StateId=18},
                new LGA(){LgTitle="Gwoza",StateId=9},
                new LGA(){LgTitle="Hadejia",StateId=18},
                new LGA(){LgTitle="Hawul",StateId=9},
                new LGA(){LgTitle="Hong",StateId=3},
                new LGA(){LgTitle="Ibadan Central",StateId=31},
                new LGA(){LgTitle="Ibadan North",StateId=31},
                new LGA(){LgTitle="Ibadan North West",StateId=31},
                new LGA(){LgTitle="Ibadan South East",StateId=31},
                new LGA(){LgTitle="Ibadan South West",StateId=31},
                new LGA(){LgTitle="Ibaji",StateId=23},
                new LGA(){LgTitle="Ibarapa Central",StateId=31},
                new LGA(){LgTitle="Ibarapa East",StateId=31},
                new LGA(){LgTitle="Ibarapa North",StateId=31},
                new LGA(){LgTitle="Ibeju/Lekki",StateId=25},
                new LGA(){LgTitle="Ibeno",StateId=4},
                new LGA(){LgTitle="Ibesikpo-Asutan",StateId=4},
                new LGA(){LgTitle="Ibi",StateId=35},
                new LGA(){LgTitle="Ibiono-Ibom",StateId=4},
                new LGA(){LgTitle="Idah",StateId=23},
                new LGA(){LgTitle="Idanre",StateId=29},
                new LGA(){LgTitle="Ideato North",StateId=17},
                new LGA(){LgTitle="Ideato South",StateId=17},
                new LGA(){LgTitle="Idemili North",StateId=5},
                new LGA(){LgTitle="Idemili South",StateId=5},
                new LGA(){LgTitle="Ido",StateId=31},
                new LGA(){LgTitle="Ido-Osi",StateId=14},
                new LGA(){LgTitle="Ifako-Ijaye",StateId=25},
                new LGA(){LgTitle="Ife Central",StateId=30},
                new LGA(){LgTitle="Ife Dayo",StateId=30},
                new LGA(){LgTitle="Ife East",StateId=30},
                new LGA(){LgTitle="Ife Lodun",StateId=30},
                new LGA(){LgTitle="Ife North",StateId=30},
                new LGA(){LgTitle="Ife South",StateId=30},
                new LGA(){LgTitle="Ifedore",StateId=29},
                new LGA(){LgTitle="Ifelodun",StateId=24},
                new LGA(){LgTitle="Ifo",StateId=28},
                new LGA(){LgTitle="Igabi",StateId=19},
                new LGA(){LgTitle="Igalamelu-Odulu",StateId=23},
                new LGA(){LgTitle="Igbo-Etiti",StateId=15},
                new LGA(){LgTitle="Igbo-Eze North",StateId=15},
                new LGA(){LgTitle="Igbo-Eze South",StateId=15},
                new LGA(){LgTitle="Iguegben ",StateId=13},
                new LGA(){LgTitle="Ihiala",StateId=5},
                new LGA(){LgTitle="Ihitte/Uboma",StateId=17},
                new LGA(){LgTitle="Ijebu East",StateId=28},
                new LGA(){LgTitle="Ijebu North",StateId=28},
                new LGA(){LgTitle="Ijebu North-East",StateId=28},
                new LGA(){LgTitle="Ijebu-Ode",StateId=28},
                new LGA(){LgTitle="Ijero",StateId=14},
                new LGA(){LgTitle="Ijumu",StateId=23},
                new LGA(){LgTitle="Ika",StateId=4},
                new LGA(){LgTitle="Ika North East",StateId=11},
                new LGA(){LgTitle="Ika South",StateId=11},
                new LGA(){LgTitle="Ikara",StateId=19},
                new LGA(){LgTitle="Ikeduru",StateId=17},
                new LGA(){LgTitle="Ikeja",StateId=25},
                new LGA(){LgTitle="Ikenne",StateId=28},
                new LGA(){LgTitle="Ikere",StateId=14},
                new LGA(){LgTitle="Ikole",StateId=14},
                new LGA(){LgTitle="Ikom",StateId=10},
                new LGA(){LgTitle="Ikono",StateId=4},
                new LGA(){LgTitle="Ikorodu",StateId=25},
                new LGA(){LgTitle="Ikot Abasi",StateId=4},
                new LGA(){LgTitle="Ikot Ekpene",StateId=4},
                new LGA(){LgTitle="Ikpoba-Okha",StateId=13},
                new LGA(){LgTitle="Ikwerre",StateId=33},
                new LGA(){LgTitle="Ikwo",StateId=12},
                new LGA(){LgTitle="Ikwuno",StateId=1},
                new LGA(){LgTitle="Ila Orangun",StateId=30},
                new LGA(){LgTitle="Ilaje",StateId=29},
                new LGA(){LgTitle="Ilejemeji",StateId=14},
                new LGA(){LgTitle="Ile-Olujiokeigbo",StateId=29},
                new LGA(){LgTitle="Ilesha East",StateId=30},
                new LGA(){LgTitle="Ilesha West",StateId=30},
                new LGA(){LgTitle="Illela",StateId=34},
                new LGA(){LgTitle="Ilorin East",StateId=24},
                new LGA(){LgTitle="Ilorin South",StateId=24},
                new LGA(){LgTitle="Ilorin West",StateId=24},
                new LGA(){LgTitle="Imeko-Afon",StateId=28},
                new LGA(){LgTitle="Ingawa",StateId=21},
                new LGA(){LgTitle="Ini",StateId=4},
                new LGA(){LgTitle="Ipokia",StateId=28},
                new LGA(){LgTitle="Irele",StateId=29},
                new LGA(){LgTitle="Irepo",StateId=31},
                new LGA(){LgTitle="Irepodun",StateId=30},
                new LGA(){LgTitle="Irepodun/Ifelodun",StateId=14},
                new LGA(){LgTitle="Irepodun-K",StateId=24},
                new LGA(){LgTitle="Irewole",StateId=30},
                new LGA(){LgTitle="Isa",StateId=34},
                new LGA(){LgTitle="Ise/Orun",StateId=14},
                new LGA(){LgTitle="Iseyin",StateId=31},
                new LGA(){LgTitle="Ishelu",StateId=12},
                new LGA(){LgTitle="Isiala Mbano",StateId=17},
                new LGA(){LgTitle="Isiala -Ngwa North",StateId=1},
                new LGA(){LgTitle="Isiala -Ngwa South",StateId=1},
                new LGA(){LgTitle="Isin",StateId=24},
                new LGA(){LgTitle="Isi-Uzo",StateId=15},
                new LGA(){LgTitle="Isokan",StateId=30},
                new LGA(){LgTitle="Isoko North",StateId=11},
                new LGA(){LgTitle="Isoko South",StateId=11},
                new LGA(){LgTitle="Isu",StateId=17},
                new LGA(){LgTitle="Isuikwuato ",StateId=1},
                new LGA(){LgTitle="Itas/Gadua",StateId=6},
                new LGA(){LgTitle="Iteswalu",StateId=31},
                new LGA(){LgTitle="Itu",StateId=4},
                new LGA(){LgTitle="Ivo",StateId=12},
                new LGA(){LgTitle="Iwajowa",StateId=31},
                new LGA(){LgTitle="Iwo",StateId=30},
                new LGA(){LgTitle="Izzi",StateId=12},
                new LGA(){LgTitle="Jaba",StateId=19},
                new LGA(){LgTitle="Jada",StateId=3},
                new LGA(){LgTitle="Jahun",StateId=18},
                new LGA(){LgTitle="Jakusko",StateId=36},
                new LGA(){LgTitle="Jalingo",StateId=35},
                new LGA(){LgTitle="Jama'are",StateId=6},
                new LGA(){LgTitle="Jega",StateId=22},
                new LGA(){LgTitle="Jema'a",StateId=19},
                new LGA(){LgTitle="Jere",StateId=9},
                new LGA(){LgTitle="Jibia",StateId=21},
                new LGA(){LgTitle="Jos East",StateId=32},
                new LGA(){LgTitle="Jos North",StateId=32},
                new LGA(){LgTitle="Jos South",StateId=32},
                new LGA(){LgTitle="Kabba/Bunu",StateId=23},
                new LGA(){LgTitle="Kabo",StateId=20},
                new LGA(){LgTitle="Kachia",StateId=19},
                new LGA(){LgTitle="Kaduna North",StateId=19},
                new LGA(){LgTitle="Kaduna South",StateId=19},
                new LGA(){LgTitle="Kafin-Hausa",StateId=18},
                new LGA(){LgTitle="Kafur",StateId=21},
                new LGA(){LgTitle="Kaga",StateId=9},
                new LGA(){LgTitle="Kagarko",StateId=19},
                new LGA(){LgTitle="Kaiama",StateId=7},
                new LGA(){LgTitle="Kaita",StateId=21},
                new LGA(){LgTitle="Kajola",StateId=31},
                new LGA(){LgTitle="Kajuru",StateId=19},
                new LGA(){LgTitle="Kala/Balge",StateId=9},
                new LGA(){LgTitle="Kalgo",StateId=22},
                new LGA(){LgTitle="Kaltungo",StateId=16},
                new LGA(){LgTitle="Kanam",StateId=32},
                new LGA(){LgTitle="Kankara",StateId=21},
                new LGA(){LgTitle="Kanke",StateId=32},
                new LGA(){LgTitle="Kankia",StateId=21},
                new LGA(){LgTitle="Kano Municipal",StateId=20},
                new LGA(){LgTitle="Karasuwa",StateId=36},
                new LGA(){LgTitle="Karaye",StateId=20},
                new LGA(){LgTitle="Karim-Lamido",StateId=35},
                new LGA(){LgTitle="Karu",StateId=26},
                new LGA(){LgTitle="Katagum",StateId=6},
                new LGA(){LgTitle="Katcha",StateId=27},
                new LGA(){LgTitle="Katsina",StateId=21},
                new LGA(){LgTitle="Katsina-Ala",StateId=8},
                new LGA(){LgTitle="Kaugama",StateId=18},
                new LGA(){LgTitle="Kaura",StateId=19},
                new LGA(){LgTitle="Kaura-Namoda",StateId=37},
                new LGA(){LgTitle="Kazaure",StateId=18},
                new LGA(){LgTitle="Keana",StateId=26},
                new LGA(){LgTitle="Kebbe",StateId=34},
                new LGA(){LgTitle="Keffi",StateId=26},
                new LGA(){LgTitle="Khana",StateId=33},
                new LGA(){LgTitle="Kibiya",StateId=20},
                new LGA(){LgTitle="Kirfi",StateId=6},
                new LGA(){LgTitle="Kiri-Kasamma",StateId=18},
                new LGA(){LgTitle="Kiru",StateId=20},
                new LGA(){LgTitle="Kiyawa",StateId=18},
                new LGA(){LgTitle="Kogi",StateId=23},
                new LGA(){LgTitle="Koko/Besse",StateId=22},
                new LGA(){LgTitle="Kokona",StateId=26},
                new LGA(){LgTitle="Kolokuma/Opkuma",StateId=7},
                new LGA(){LgTitle="Konduga",StateId=9},
                new LGA(){LgTitle="Kontagara",StateId=27},
                new LGA(){LgTitle="Koshinsha-Tse",StateId=8},
                new LGA(){LgTitle="Kosofe",StateId=25},
                new LGA(){LgTitle="Kubau",StateId=19},
                new LGA(){LgTitle="Kudan",StateId=19},
                new LGA(){LgTitle="Kuje",StateId=2},
                new LGA(){LgTitle="Kukawa",StateId=9},
                new LGA(){LgTitle="Kumbotso",StateId=20},
                new LGA(){LgTitle="Kunchi",StateId=20},
                new LGA(){LgTitle="Kura",StateId=20},
                new LGA(){LgTitle="Kurfi",StateId=21},
                new LGA(){LgTitle="Kurmi",StateId=35},
                new LGA(){LgTitle="Kusada",StateId=21},
                new LGA(){LgTitle="Kwali",StateId=1},
                new LGA(){LgTitle="Kwami",StateId=16},
                new LGA(){LgTitle="Kwande",StateId=8},
                new LGA(){LgTitle="Kware",StateId=34},
                new LGA(){LgTitle="Kwaya Kusar",StateId=9},
                new LGA(){LgTitle="Lafia",StateId=26},
                new LGA(){LgTitle="Lagelu",StateId=31},
                new LGA(){LgTitle="Lagos Island",StateId=25},
                new LGA(){LgTitle="Lagos Mainland",StateId=25},
                new LGA(){LgTitle="Lamurde",StateId=3},
                new LGA(){LgTitle="Langtang North",StateId=32},
                new LGA(){LgTitle="Langtang South",StateId=32},
                new LGA(){LgTitle="Lapai",StateId=27},
                new LGA(){LgTitle="Lau",StateId=35},
                new LGA(){LgTitle="Lavun",StateId=27},
                new LGA(){LgTitle="Lere",StateId=19},
                new LGA(){LgTitle="Logo",StateId=8},
                new LGA(){LgTitle="Lokoja",StateId=23},
                new LGA(){LgTitle="Machina",StateId=36},
                new LGA(){LgTitle="Madagali",StateId=3},
                new LGA(){LgTitle="Madobi",StateId=20},
                new LGA(){LgTitle="Mafa",StateId=9},
                new LGA(){LgTitle="Magama",StateId=27},
                new LGA(){LgTitle="Magumeri",StateId=9},
                new LGA(){LgTitle="Mai'adua",StateId=21},
                new LGA(){LgTitle="Maiduguri",StateId=9},
                new LGA(){LgTitle="Maigatari",StateId=18},
                new LGA(){LgTitle="Maiha",StateId=3},
                new LGA(){LgTitle="Maiyama",StateId=22},
                new LGA(){LgTitle="Makarfi",StateId=19},
                new LGA(){LgTitle="Makoda",StateId=20},
                new LGA(){LgTitle="Makurdi",StateId=8},
                new LGA(){LgTitle="Malam-Maduri",StateId=18},
                new LGA(){LgTitle="Malumfashi",StateId=21},
                new LGA(){LgTitle="Mangu",StateId=32},
                new LGA(){LgTitle="Mani",StateId=21},
                new LGA(){LgTitle="Maraduna",StateId=37},
                new LGA(){LgTitle="Mariga",StateId=27},
                new LGA(){LgTitle="Marte",StateId=9},
                new LGA(){LgTitle="Maru",StateId=37},
                new LGA(){LgTitle="Mashegu",StateId=27},
                new LGA(){LgTitle="Mashi",StateId=21},
                new LGA(){LgTitle="Matazu",StateId=21},
                new LGA(){LgTitle="Mayo Belwa",StateId=3},
                new LGA(){LgTitle="Mbaitoli",StateId=17},
                new LGA(){LgTitle="Mbo",StateId=4},
                new LGA(){LgTitle="Michika",StateId=3},
                new LGA(){LgTitle="Miga",StateId=18},
                new LGA(){LgTitle="Mikang",StateId=32},
                new LGA(){LgTitle="Mingi",StateId=6},
                new LGA(){LgTitle="Minijibir",StateId=20},
                new LGA(){LgTitle="Misau",StateId=6},
                new LGA(){LgTitle="Mkpat-Enin",StateId=4},
                new LGA(){LgTitle="Moba",StateId=14},
                new LGA(){LgTitle="Mobbar",StateId=9},
                new LGA(){LgTitle="Mokwa",StateId=27},
                new LGA(){LgTitle="Monguno",StateId=9},
                new LGA(){LgTitle="Mopa-Muro",StateId=23},
                new LGA(){LgTitle="Moro",StateId=24},
                new LGA(){LgTitle="Mubi North",StateId=3},
                new LGA(){LgTitle="Mubi South",StateId=3},
                new LGA(){LgTitle="Musawa",StateId=21},
                new LGA(){LgTitle="Mushin",StateId=25},
                new LGA(){LgTitle="Muyu",StateId=27},
                new LGA(){LgTitle="Nafada",StateId=16},
                new LGA(){LgTitle="Nangere",StateId=36},
                new LGA(){LgTitle="Nassarawa",StateId=26},
                new LGA(){LgTitle="Nassarawa-Eggon",StateId=26},
                new LGA(){LgTitle="Nassarawa-K",StateId=20},
                new LGA(){LgTitle="Ndokwa East",StateId=11},
                new LGA(){LgTitle="Ndokwa West",StateId=11},
                new LGA(){LgTitle="Nembe",StateId=7},
                new LGA(){LgTitle="Ngala",StateId=9},
                new LGA(){LgTitle="Nganzai",StateId=9},
                new LGA(){LgTitle="Ngaski",StateId=22},
                new LGA(){LgTitle="Ngor-Opkala",StateId=17},
                new LGA(){LgTitle="Nguru",StateId=36},
                new LGA(){LgTitle="Njaba",StateId=17},
                new LGA(){LgTitle="Njikoka",StateId=5},
                new LGA(){LgTitle="Nkanu East",StateId=15},
                new LGA(){LgTitle="Nkanu West",StateId=15},
                new LGA(){LgTitle="Nkwerre",StateId=17},
                new LGA(){LgTitle="Nnewi North",StateId=5},
                new LGA(){LgTitle="Nnewi South",StateId=5},
                new LGA(){LgTitle="Nsit Atai",StateId=4},
                new LGA(){LgTitle="Nsit Ibom",StateId=4},
                new LGA(){LgTitle="Nsit Ubium",StateId=4},
                new LGA(){LgTitle="Nsukka",StateId=15},
                new LGA(){LgTitle="Numan",StateId=3},
                new LGA(){LgTitle="Nwangele",StateId=17},
                new LGA(){LgTitle="Obafemi-Owode",StateId=28},
                new LGA(){LgTitle="Obanliku",StateId=10},
                new LGA(){LgTitle="Obgomosho North",StateId=31},
                new LGA(){LgTitle="Obi",StateId=8},
                new LGA(){LgTitle="Obi-N",StateId=26},
                new LGA(){LgTitle="Obio / Akpor",StateId=33},
                new LGA(){LgTitle="Obioma-Ngwa",StateId=1},
                new LGA(){LgTitle="Obokun",StateId=30},
                new LGA(){LgTitle="Obot Akara",StateId=4},
                new LGA(){LgTitle="Obowo",StateId=17},
                new LGA(){LgTitle="Obubra",StateId=10},
                new LGA(){LgTitle="Obudo",StateId=10},
                new LGA(){LgTitle="Odedah",StateId=28},
                new LGA(){LgTitle="Odigbo",StateId=29},
                new LGA(){LgTitle="Odogbolu",StateId=28},
                new LGA(){LgTitle="Odo-Otin",StateId=30},
                new LGA(){LgTitle="Odukpani",StateId=10},
                new LGA(){LgTitle="Offa",StateId=24},
                new LGA(){LgTitle="Ofu",StateId=23},
                new LGA(){LgTitle="Ogba / Egbema/Ndoni",StateId=33},
                new LGA(){LgTitle="Ogbadibo",StateId=8},
                new LGA(){LgTitle="Ogbaru",StateId=5},
                new LGA(){LgTitle="Ogbia",StateId=7},
                new LGA(){LgTitle="Ogbomosho South",StateId=31},
                new LGA(){LgTitle="Ogoja",StateId=10},
                new LGA(){LgTitle="Ogori/Magongo",StateId=23},
                new LGA(){LgTitle="Ogu / Bolo",StateId=33},
                new LGA(){LgTitle="Ogun Water Side",StateId=28},
                new LGA(){LgTitle="Oguta",StateId=17},
                new LGA(){LgTitle="Ohafia",StateId=1},
                new LGA(){LgTitle="Ohaji/Egbema",StateId=17},
                new LGA(){LgTitle="Ohaozara",StateId=12},
                new LGA(){LgTitle="Ohaukwu",StateId=12},
                new LGA(){LgTitle="Ohimini",StateId=8},
                new LGA(){LgTitle="Oji-River",StateId=15},
                new LGA(){LgTitle="Ojo",StateId=25},
                new LGA(){LgTitle="Oju",StateId=8},
                new LGA(){LgTitle="Oke-Ero",StateId=24},
                new LGA(){LgTitle="Okehi",StateId=23},
                new LGA(){LgTitle="Okene",StateId=23},
                new LGA(){LgTitle="Okigwe",StateId=17},
                new LGA(){LgTitle="Okitipupa",StateId=29},
                new LGA(){LgTitle="Okobo",StateId=4},
                new LGA(){LgTitle="Okpe",StateId=11},
                new LGA(){LgTitle="Okpokwu",StateId=8},
                new LGA(){LgTitle="Okrika",StateId=33},
                new LGA(){LgTitle="Olamaboro",StateId=23},
                new LGA(){LgTitle="Ola-Oluwa",StateId=30},
                new LGA(){LgTitle="Olarunda",StateId=30},
                new LGA(){LgTitle="Olurunsogo",StateId=31},
                new LGA(){LgTitle="Oluyola",StateId=31},
                new LGA(){LgTitle="Omala",StateId=23},
                new LGA(){LgTitle="Omumma",StateId=33},
                new LGA(){LgTitle="Ona-Ora",StateId=31},
                new LGA(){LgTitle="Ondo East",StateId=29},
                new LGA(){LgTitle="Ondo West",StateId=29},
                new LGA(){LgTitle="Onicha",StateId=12},
                new LGA(){LgTitle="Onitsha North",StateId=5},
                new LGA(){LgTitle="Onitsha South",StateId=5},
                new LGA(){LgTitle="Onna",StateId=4},
                new LGA(){LgTitle="Onuimo",StateId=17},
                new LGA(){LgTitle="Opobo / Nkoro",StateId=33},
                new LGA(){LgTitle="Orelope",StateId=31},
                new LGA(){LgTitle="Orendo",StateId=13},
                new LGA(){LgTitle="Orhionmwon",StateId=13},
                new LGA(){LgTitle="Oriade",StateId=30},
                new LGA(){LgTitle="Ori-Ire",StateId=31},
                new LGA(){LgTitle="Orlu",StateId=17},
                new LGA(){LgTitle="Orolu",StateId=30},
                new LGA(){LgTitle="Oron",StateId=4},
                new LGA(){LgTitle="Orsu",StateId=17},
                new LGA(){LgTitle="Oru East",StateId=17},
                new LGA(){LgTitle="Oru West",StateId=17},
                new LGA(){LgTitle="Oruk Anam",StateId=4},
                new LGA(){LgTitle="Orumba North",StateId=5},
                new LGA(){LgTitle="Orumba South",StateId=5},
                new LGA(){LgTitle="Ose",StateId=29},
                new LGA(){LgTitle="Oshimili North",StateId=11},
                new LGA(){LgTitle="Oshimili South",StateId=11},
                new LGA(){LgTitle="Oshodi-Isolo",StateId=25},
                new LGA(){LgTitle="Osisioma-Ngwa",StateId=1},
                new LGA(){LgTitle="Osogbo",StateId=30},
                new LGA(){LgTitle="Oturkpo",StateId=8},
                new LGA(){LgTitle="Ovia North East",StateId=13},
                new LGA(){LgTitle="Ovia South West",StateId=13},
                new LGA(){LgTitle="Owan East",StateId=13},
                new LGA(){LgTitle="Owan West",StateId=13},
                new LGA(){LgTitle="Owerri Municipal",StateId=17},
                new LGA(){LgTitle="Owerri North",StateId=17},
                new LGA(){LgTitle="Owerri West",StateId=17},
                new LGA(){LgTitle="Owo",StateId=29},
                new LGA(){LgTitle="Oye",StateId=14},
                new LGA(){LgTitle="Oyi",StateId=5},
                new LGA(){LgTitle="Oyigbo",StateId=33},
                new LGA(){LgTitle="Oyo East",StateId=31},
                new LGA(){LgTitle="Oyo West",StateId=31},
                new LGA(){LgTitle="Oyun",StateId=24},
                new LGA(){LgTitle="Paikoro",StateId=27},
                new LGA(){LgTitle="Pankshin",StateId=32},
                new LGA(){LgTitle="Patani",StateId=11},
                new LGA(){LgTitle="Pategi",StateId=24},
                new LGA(){LgTitle="Port-Harcourt",StateId=33},
                new LGA(){LgTitle="Potiskum",StateId=36},
                new LGA(){LgTitle="Qua'anpan",StateId=32},
                new LGA(){LgTitle="Rabah",StateId=34},
                new LGA(){LgTitle="Rafi",StateId=27},
                new LGA(){LgTitle="Rano",StateId=20},
                new LGA(){LgTitle="Remo North",StateId=28},
                new LGA(){LgTitle="Rijau",StateId=27},
                new LGA(){LgTitle="Rimi",StateId=21},
                new LGA(){LgTitle="Rimin Gado",StateId=20},
                new LGA(){LgTitle="Ringin",StateId=18},
                new LGA(){LgTitle="Riyom Shendam",StateId=32},
                new LGA(){LgTitle="Rogo",StateId=20},
                new LGA(){LgTitle="Roni",StateId=18},
                new LGA(){LgTitle="Sabon Gari",StateId=19},
                new LGA(){LgTitle="Sabon-Birni",StateId=34},
                new LGA(){LgTitle="Sabuwa",StateId=21},
                new LGA(){LgTitle="Safana",StateId=21},
                new LGA(){LgTitle="Sagbama",StateId=7},
                new LGA(){LgTitle="Sakaba",StateId=22},
                new LGA(){LgTitle="Saki East",StateId=31},
                new LGA(){LgTitle="Saki West",StateId=31},
                new LGA(){LgTitle="Sandamu",StateId=21},
                new LGA(){LgTitle="Sanga",StateId=19},
                new LGA(){LgTitle="Sapele",StateId=11},
                new LGA(){LgTitle="Saradauna",StateId=35},
                new LGA(){LgTitle="Shagamu",StateId=28},
                new LGA(){LgTitle="Shagari",StateId=34},
                new LGA(){LgTitle="Shanga",StateId=22},
                new LGA(){LgTitle="Shani",StateId=9},
                new LGA(){LgTitle="Shanono",StateId=20},
                new LGA(){LgTitle="Shelleng",StateId=3},
                new LGA(){LgTitle="Shendam",StateId=32},
                new LGA(){LgTitle="Shinkafi",StateId=37},
                new LGA(){LgTitle="Shira",StateId=6},
                new LGA(){LgTitle="Shiroro",StateId=27},
                new LGA(){LgTitle="Shomgom",StateId=16},
                new LGA(){LgTitle="Shomolu",StateId=25},
                new LGA(){LgTitle="Silame",StateId=34},
                new LGA(){LgTitle="Soba",StateId=19},
                new LGA(){LgTitle="Sokoto North",StateId=34},
                new LGA(){LgTitle="Sokoto South",StateId=34},
                new LGA(){LgTitle="Song",StateId=3},
                new LGA(){LgTitle="Suleja",StateId=27},
                new LGA(){LgTitle="Sule-Tankarka",StateId=18},
                new LGA(){LgTitle="Sumaila",StateId=20},
                new LGA(){LgTitle="Suru",StateId=22},
                new LGA(){LgTitle="Surulere",StateId=25},
                new LGA(){LgTitle="Surulere-O",StateId=31},
                new LGA(){LgTitle="Tafa",StateId=27},
                new LGA(){LgTitle="Tafawa-Balewa",StateId=6},
                new LGA(){LgTitle="Tai",StateId=33},
                new LGA(){LgTitle="Takai",StateId=20},
                new LGA(){LgTitle="Takum",StateId=35},
                new LGA(){LgTitle="Talata Marafa",StateId=37},
                new LGA(){LgTitle="Tambuwal",StateId=34},
                new LGA(){LgTitle="Tangaza",StateId=34},
                new LGA(){LgTitle="Tarauni",StateId=20},
                new LGA(){LgTitle="Tarka",StateId=8},
                new LGA(){LgTitle="Tarmua",StateId=36},
                new LGA(){LgTitle="Taura",StateId=18},
                new LGA(){LgTitle="Tofa",StateId=20},
                new LGA(){LgTitle="Toro",StateId=6},
                new LGA(){LgTitle="Toto",StateId=26},
                new LGA(){LgTitle="Toungo",StateId=3},
                new LGA(){LgTitle="Tsafe",StateId=37},
                new LGA(){LgTitle="Tsanyawa",StateId=20},
                new LGA(){LgTitle="Tudun Wada",StateId=20},
                new LGA(){LgTitle="Tureta",StateId=34},
                new LGA(){LgTitle="Udenu",StateId=15},
                new LGA(){LgTitle="Udi",StateId=15},
                new LGA(){LgTitle="Udu",StateId=11},
                new LGA(){LgTitle="Udung Uko",StateId=4},
                new LGA(){LgTitle="Ughelli North",StateId=11},
                new LGA(){LgTitle="Ughelli South",StateId=11},
                new LGA(){LgTitle="Ugwunagbo",StateId=1},
                new LGA(){LgTitle="Ukanafun",StateId=4},
                new LGA(){LgTitle="Ukum",StateId=8},
                new LGA(){LgTitle="Ukwa East",StateId=1},
                new LGA(){LgTitle="Ukwa West",StateId=1},
                new LGA(){LgTitle="Ukwuani",StateId=11},
                new LGA(){LgTitle="Umaahia South",StateId=1},
                new LGA(){LgTitle="Umuahia North",StateId=1},
                new LGA(){LgTitle="Umunmwonde",StateId=13},
                new LGA(){LgTitle="Umu-Nneochi",StateId=1},
                new LGA(){LgTitle="Ungogo",StateId=20},
                new LGA(){LgTitle="Uruan",StateId=4},
                new LGA(){LgTitle="Urue/O/Oruko",StateId=4},
                new LGA(){LgTitle="Ushongo",StateId=8},
                new LGA(){LgTitle="Ussa",StateId=35},
                new LGA(){LgTitle="Uvwie",StateId=11},
                new LGA(){LgTitle="Uyo",StateId=4},
                new LGA(){LgTitle="Uzo-Uwani",StateId=15},
                new LGA(){LgTitle="Vandeikya",StateId=8},
                new LGA(){LgTitle="Wamakko",StateId=34},
                new LGA(){LgTitle="Wamba",StateId=26},
                new LGA(){LgTitle="Warawa",StateId=20},
                new LGA(){LgTitle="Warji",StateId=6},
                new LGA(){LgTitle="Warri North",StateId=11},
                new LGA(){LgTitle="Warri South",StateId=11},
                new LGA(){LgTitle="Warri South-West",StateId=11},
                new LGA(){LgTitle="Wasagu/Danko",StateId=22},
                new LGA(){LgTitle="Wase",StateId=32},
                new LGA(){LgTitle="Wudil",StateId=20},
                new LGA(){LgTitle="Wukari",StateId=35},
                new LGA(){LgTitle="Wurno",StateId=34},
                new LGA(){LgTitle="Wushishi",StateId=27},
                new LGA(){LgTitle="Yabo",StateId=34},
                new LGA(){LgTitle="Yagba East",StateId=23},
                new LGA(){LgTitle="Yagba West",StateId=23},
                new LGA(){LgTitle="Yakurr",StateId=10},
                new LGA(){LgTitle="Yala",StateId=10},
                new LGA(){LgTitle="Yamaltu/Deba",StateId=16},
                new LGA(){LgTitle="Yankwashi",StateId=18},
                new LGA(){LgTitle="Yauri",StateId=22},
                new LGA(){LgTitle="Yenegoa",StateId=7},
                new LGA(){LgTitle="Yola North",StateId=3},
                new LGA(){LgTitle="Yola South",StateId=3},
                new LGA(){LgTitle="Yorro",StateId=35},
                new LGA(){LgTitle="Yunusari",StateId=36},
                new LGA(){LgTitle="Yusufari",StateId=36},
                new LGA(){LgTitle="Zaki",StateId=6},
                new LGA(){LgTitle="Zango",StateId=21},
                new LGA(){LgTitle="Zangon-Kataf",StateId=19},
                new LGA(){LgTitle="Zaria",StateId=19},
                new LGA(){LgTitle="Zing",StateId=35},
                new LGA(){LgTitle="Zurmi",StateId=37},
                new LGA(){LgTitle="Zuru",StateId=22}

            };

            foreach (var l in lgs)
            {
                context.Lga.Add(l);
                context.SaveChanges();
            }*/

            var sessions = new List<Session>

            {
                
                new Session{SessionId=20,Title="2020/2021"},
                new Session{SessionId=21,Title="2021/2022"},
            };
            foreach (var s in sessions)
            {
                context.Session.Add(s);
                context.SaveChanges();
            }

            var semesters = new List<Semester>
            {
                
                new Semester{SemesterId=201,SemesterTitle="1st Semester",SessionId=20},
                new Semester{SemesterId=202,SemesterTitle="2nd Semester",SessionId=20},
                new Semester{SemesterId=211,SemesterTitle="1st Semester",SessionId=21},
                new Semester{SemesterId=212,SemesterTitle="2nd Semester",SessionId=21}
            };

            foreach (var s in semesters)
            {
                context.Semester.Add(s);
                context.SaveChanges();
            }

             
        }
    }
}
